name: Commit Message Check

on:
  push:
    branches:
      - '*'  # Replace with your main branch name or use '*' for all branches

jobs:
  commit-message-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Validate commit messages
        run: |
          regex="^(feat|fix|docs|style|refactor|perf|test|chore|add)(\(.+\))?: .{1,50}$"
          while IFS= read -r line; do
            if ! echo "$line" | grep -E "$regex"; then
              echo "Invalid commit message: $line"
              exit 1
            fi
          done < <(git log --format=%s origin/main..HEAD)
